---
title: "GIS Final Project"
author: "Homar A. Maurás Rodríguez"
format: html
editor: visual
execute: 
  echo: false
  error: false
---

```{r libraries}
library(tidyverse)
library(dplyr)
library(sf)
library(leaflet)
library(mapview)
library(lubridate)
```

```{r datasets}
acled <- read.csv('/Users/homi/Data Science/datasets/acled_aggregated_20060.csv')
confessional <- read_csv('/Users/homi/Data Science/datasets/adm1_confessional.csv')
lebanon_adm1 <- st_read("/Users/homi/Data Science/datasets/geoBoundaries-LBN-ADM1-all/geoBoundaries-LBN-ADM1.shp")
```

```{r formatting}
#lowercase
names(acled) <- tolower(names(acled))
names(confessional) <- tolower(names(confessional))
names(lebanon_adm1) <- tolower(names(lebanon_adm1))

#selecting relevant variables
acled <- acled %>% select(admin1, event.month, sub.event.type, events)
lebanon_adm1 <- lebanon_adm1 %>% select(shapename, shapeiso, geometry)

#renaming variables
acled <- acled %>% rename(adm1 = admin1, event_month = event.month, event_type = sub.event.type)
confessional <- confessional %>% rename(iso = iso_3166_2, sect = reported_sect, adm1_sect = adm1_total)
lebanon_adm1 <- lebanon_adm1 %>% rename(adm1 = shapename, iso = shapeiso)

#replace event_month dates with corresponding month name (using lubridate)
acled$event_month <- ymd(acled$event_month) #converting event_month into date format
acled$prior_month <- floor_date(acled$event_month - days(1), "month") #adjust to the prior month by subtracting one day, then getting the first day of that month
acled$prior_month <- format(acled$prior_month, "%B, %Y") #format the 'prior_month' column as "Month, Year"
acled <- acled %>% relocate(prior_month, .before = event_month) #changing column order
head(acled$prior_month)
```

```{r names}
# replace sect to Christian, Shia, Sunni, Druze, and Other
confessional <- confessional %>%
  mutate(sect = if_else(sect %in% c("Armenian Catholic", "Armenian Orthodox", 
                                    "Christian Minorities", "Greek Catholic", 
                                    "Greek Orthodox", "Maronite", "Protestant"), 
                        "Christian", sect)) #replacing christian groups into broader christian category
confessional <- confessional %>%
  mutate(sect = if_else(sect %in% "Alawite", 
                        "Shia", sect)) #including Alawite in Shia faith
head(confessional$sect)

#replacing adm1 names to english
confessional <- confessional %>% #changing confessional
  mutate(adm1 = if_else(adm1 %in% "Bayrut", "Beirut", adm1),
         adm1 = if_else(adm1 %in% "Beqaa", "Bekaa", adm1),
         adm1 = if_else(adm1 %in% "Liban-Nord", "North", adm1),
         adm1 = if_else(adm1 %in% "Liban-Sud", "South", adm1),
         adm1 = if_else(adm1 %in% "Mont-Liban", "Mount Lebanon", adm1),
         adm1 = if_else(adm1 %in% "Nabatiye", "Al Nabatieh", adm1)) 
unique(confessional$adm1)

lebanon_adm1 <- lebanon_adm1 %>%
  mutate(adm1 = if_else(adm1 %in% "Aakkâr", "Akkar", adm1),
         adm1 = if_else(adm1 %in% "Nabatîyé", "Al Nabatieh", adm1),
         adm1 = if_else(adm1 %in% "Beyrouth", "Beirut", adm1),
         adm1 = if_else(adm1 %in% "Béqaa", "Bekaa", adm1),
         adm1 = if_else(adm1 %in% "Liban-Nord", "North", adm1),
         adm1 = if_else(adm1 %in% "Mont-Liban", "Mount Lebanon", adm1),
         adm1 = if_else(adm1 %in% "Liban-Sud", "South", adm1),
         adm1 = if_else(adm1 %in% "Nabatîyé", "Al Nabatieh", adm1),
         )
unique(lebanon_adm1$adm1)
unique(acled$adm1)
```


```{r union}
#combining Jbeil with Mount Lebanon using st_union
###view the original map
adm1_map <- lebanon_adm1 %>%
  select(adm1, geometry) %>%
  mapview()
adm1_map

lebanon_union <- lebanon_adm1 %>%
  mutate(adm1 = ifelse(adm1 == "Keserwan-Jbeil", "Mount Lebanon", adm1)) %>%
  group_by(adm1, iso) %>%
  summarize(geometry = st_union(geometry), .groups = "drop")

#checking the updated geometries
unique(lebanon_union$adm1)
union_map <- lebanon_union %>%
  select(adm1, geometry) %>%
  mapview()
union_map 

#THE SOUTHERN BORDER OF JBEIL DID NOT DISAPPEAR
```


```{r descriptive_religion}
sect_summary <- confessional %>%
  group_by(sect) %>%
  summarise(sum = sum(adm1_sect)) %>%
  arrange(desc(sum))
sect_summary 
```

```{r join}

```
